String getUserByIdQuery = """
 query getUserById(\$id: String!){
  getUserById(id: \$id){
    email
    username
    folders{
      id
      cards{
        ... on CardDigimon {
          __typename
          id
          type
          name
          color
          attackPoints
          healthPoints
          energyCount
          level
          evolution {
            name
          }
        }
        ... on CardEnergy {
          __typename
          id
          type
          name
          color
          energyCount
        }
        ... on CardSummonDigimon {
          __typename
          id
          type
          name
          digimonsCards{
            name
            color
            attackPointsCardSummonDigimon: attackPoints
            healthPointsCardSummonDigimon: healthPoints
            energyCount
            level
            evolution {
              name
            }
          }
        }
        ... on CardEquipment {
          __typename
          id
          type
          name
          attackPointsCardEquipment : attackPoints
          healthPointsCardEquipment : healthPoints
          quantityOfTargets
          targetScope
        }
      }
      name
      colors{
        green
        red
        blue
        white
        black
      }
    }
  }
}

""";

String getAllCards = """
query getCards {
  cards {
    ... on CardDigimon {
          __typename
      type
      	id
      autoGeneratedId
          name
          color
          attackPoints
          healthPoints
          energyCount
          level
          evolution {
            name
            color
            attackPoints
            healthPoints
          }
        }
        ... on CardEnergy {
          __typename
      	id
      type
      autoGeneratedId
          
          name
          color
          energyCount
        }
        ... on CardSummonDigimon {
          __typename
      	id
          name
      type
      autoGeneratedId
          
          digimonsCards{
            name
            color
            attackPointsCardSummonDigimon: attackPoints
            healthPointsCardSummonDigimon: healthPoints
            energyCount
            level
          }
        }
        ... on CardEquipment {
          __typename
      	id
      type
      autoGeneratedId
          
          name
          attackPointsCardEquipment : attackPoints
          healthPointsCardEquipment : healthPoints
          quantityOfTargets
          targetScope
        }
  }
}

""";

String getFolderById = """
query getFolderById(\$userId: String!, \$folderId: String!){
  getFolderById(getFolderByIdInput: {
    userId: \$userId,
    folderId: \$folderId
  }){
    id
    name
   cards {
    ... on CardDigimon {
          __typename
      type
      	id
      autoGeneratedId
          name
          color
          attackPoints
          healthPoints
          energyCount
          level
          evolution {
            name
            color
            attackPoints
            healthPoints
          }
        }
        ... on CardEnergy {
          __typename
      	id
      type
      autoGeneratedId
          
          name
          color
          energyCount
        }
        ... on CardSummonDigimon {
          __typename
      	id
          name
      type
      autoGeneratedId
          
          digimonsCards{
            name
            color
            attackPointsCardSummonDigimon: attackPoints
            healthPointsCardSummonDigimon: healthPoints
            energyCount
            level
          }
        }
        ... on CardEquipment {
          __typename
      	  id
          type
          autoGeneratedId
          
          name
          attackPointsCardEquipment : attackPoints
          healthPointsCardEquipment : healthPoints
          quantityOfTargets
          targetScope
        }
  }
  }
}
""";

String getAvailableCardsToPutInDeck = """
query getAvailableCardsToPutInDeck(\$userId: String!){
  getAvailableCardsToPutInDeck(userId: \$userId){
    quantity
    card{
      	... on CardDigimon {
          name
          id
          color
          type
        }
				... on CardEnergy {
          id
          name
          color
          type
        }
        ... on CardSummonDigimon {
          id
          name
          type
        }
        ... on CardEquipment {
          __typename
          id
          type
          name
        }

    }
  }
}
""";

String getStoreCardsByUserId = """
query getAvailableCardsToPurchase(\$userId: String!){
  getAvailableCardsToPurchase(userId: \$userId){
    quantity
    card{
      	... on CardDigimon {
          __typename
          id
          name
          color
          attackPoints
          healthPoints
          energyCount
          level
          type
          price
          evolution {
            name
            color
            attackPoints
            healthPoints
          }
        }
        ... on CardEnergy {
          __typename
          id
          name
          color
          price
          type
          energyCount
        }
        ... on CardSummonDigimon {
          __typename
          id
          name
          type
          price
          digimonsCards{
            name
            color
            attackPointsCardSummonDigimon: attackPoints
            healthPointsCardSummonDigimon: healthPoints
            energyCount
            level
          }
        }
        ... on CardEquipment {
          __typename
          id
          type
          autoGeneratedId
          name
          price
          attackPointsCardEquipment : attackPoints
          healthPointsCardEquipment : healthPoints
          quantityOfTargets
          targetScope
        }
    }
  }
}

""";

String getUserByEmail = """
query getUserByEmail(\$email: String!){
  getUserByEmail(email: \$email){
    id
    email
    username
    coins
    role
    avatarUrl
  }
}

""";
